#!/usr/bin/env python
#######################################################################################
# The PenTesters Framework (PTF) - Automatic Penetration Testing Platform Creation
# Written by: David Kennedy (ReL1K)
# Twitter: @TrustedSec
# Website: https://www.trustedsec.com
#######################################################################################

import sys
import subprocess
import os

if os.geteuid() != 0:
	print "\nThe Pentesters Framework (PTF) - by David Kennedy (ReL1K)"
	print "\nThis needs to be run as root. Please sudo it up! Exiting..."
	exit()

try:
	# try to update ourself first
	print "[*] Trying to update myself first.. Then starting framework."
	subprocess.Popen("git pull", shell=True).wait()

	# pull in the framework
	from src.core import *
	import src.framework

except KeyboardInterrupt:
	print "\n"
	exit_ptf()
	sys.exit()

except Exception, e:
	print ("[!] DANGER WILL ROBINSON. DANGER WILL ROBINSON. Error has occured.")
	print ("[!] It's not possible its due to my coding skillz, it must be you? :-)")
	print ("[!] Printing that error. Get that error. You get it: " + str(e))
